services:
  mysql:
    image: mysql:8.0
    container_name: kube_credential_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kube_credential_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - kube_credential_network

  issuance-service:
    build:
      context: ./backend
      dockerfile: issuance-service/Dockerfile  # ← CORRECT PATH
    container_name: issuance_service
    environment:
      DB_HOST: mysql
      DB_USER: app_user
      DB_PASSWORD: app_password
      DB_NAME: kube_credential_db
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - kube_credential_network

  verification-service:
    build:
      context: ./backend
      dockerfile: verification-service/Dockerfile  # ← CORRECT PATH
    container_name: verification_service
    environment:
      DB_HOST: mysql
      DB_USER: app_user
      DB_PASSWORD: app_password
      DB_NAME: kube_credential_db
      PORT: 3002
    ports:
      - "3002:3002"
    depends_on:
      - mysql
    networks:
      - kube_credential_network

  frontend:
    build: ./frontend
    container_name: kube_credential_frontend
    ports:
      - "3000:3000"
    depends_on:
      - issuance-service
      - verification-service
    networks:
      - kube_credential_network

volumes:
  mysql_data:

networks:
  kube_credential_network:
    driver: bridge