version: '3.8'
services:
  mysql:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: kube_credential
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
  issuance:
    build: ./backend/issuance-service
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: example
      DB_DATABASE: kube_credential
      ISSUANCE_PORT: 4000
    depends_on:
      - mysql
    ports:
      - '4000:4000'
  verification:
    build: ./backend/verification-service
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: example
      DB_DATABASE: kube_credential
      VERIFICATION_PORT: 5000
    depends_on:
      - mysql
    ports:
      - '5000:5000'
  frontend:
    build: ./frontend
    ports:
      - '8080:80'
    depends_on:
      - issuance
      - verification
volumes:
  db_data: