# docker-compose.yml
version: '3.8'

services:
  # Issuance Service
  issuance-service:
    build: ./backend/issuance-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=./data/issuance.db
      - POD_NAME=issuance-pod-1
    volumes:
      - issuance-data:/app/data

  # Verification Service  
  verification-service:
    build: ./backend/verification-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - DATABASE_URL=./data/verification.db
      - POD_NAME=verification-pod-1
    volumes:
      - verification-data:/app/data

  # Frontend
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - issuance-service
      - verification-service

volumes:
  issuance-data:
  verification-data: