apiVersion: apps/v1
kind: Deployment
metadata:
  name: issuance-deployment
  labels:
    app: issuance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: issuance
  template:
    metadata:
      labels:
        app: issuance
    spec:
      containers:
        - name: issuance
          image: your-dockerhub-username/issuance:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              value: root
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: DB_NAME
              value: kube_credential
            - name: WORKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: issuance-service
spec:
  selector:
    app: issuance
  ports:
    - port: 80
      targetPort: 8081
  type: ClusterIP
