apiVersion: apps/v1
kind: Deployment
metadata:
  name: verification-deployment
  labels:
    app: verification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: verification
  template:
    metadata:
      labels:
        app: verification
    spec:
      containers:
        - name: verification
          image: your-dockerhub-username/verification:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              value: root
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: DB_NAME
              value: kube_credential
            - name: WORKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: verification-service
spec:
  selector:
    app: verification
  ports:
    - port: 80
      targetPort: 8082
  type: ClusterIP
